# Generated by Django 3.1.1 on 2020-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='email сотрудника')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('is_active', models.IntegerField(default=1, verbose_name='Признак активности. 0 - не активный, 1 - активный. По умолчанию 1')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего входа в систему')),
                ('rowversion', models.DateField(blank=True, null=True, verbose_name='Дата и время изменения')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон сотрудника')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='Аватарка')),
                ('image_url_orig', models.TextField(blank=True, null=True, verbose_name='Аватар оригинал')),
                ('is_show_all_remonts', models.IntegerField(default=0, verbose_name='Показывать вес ремонты для данной должности')),
                ('is_write_chat_message', models.IntegerField(default=0, verbose_name='Может ли писать в чат (1 - да, 0 - нет')),
                ('mobile_token_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Первые 10 символов от mobile')),
                ('is_kpi', models.IntegerField(default=0, verbose_name='Возможность проставлять KPI')),
                ('is_only_read', models.IntegerField(default=0, verbose_name='1 - пользователь только для чтения, 0 - обычный наш пользователь')),
                ('is_subscribe', models.IntegerField(default=0, verbose_name='Подписан ли пользователь на уведомления. 0 - не подписан, 1 - подписан')),
                ('application_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='На какое приложение отправлять пуш уведомление')),
                ('guid', models.CharField(blank=True, max_length=250, null=True, verbose_name='ГУИД для хантеров в 1С')),
                ('auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
